version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=mystore
  web:
    build: .
    restart: unless-stopped
    command: npm start
    volumes:
      - .:/usr/app/node
    ports:
      - "5000:5000"
    depends_on:
      - postgres
